### ISSUE TITLE
How to handle audio?

### ISSUE THREAD

**Issue by adworacz** [Irrational-Encoding-Wizardry/vs-source#15]
First of all, thank you for putting this cool project together! I think it might save me a fair bit of time!

my one question is that this seems to be focused on extracting the video from a dvd folder structure in an iso. 

How is audio expected to be handled?

At first blush, it seems like one would have to open the iso themselves and demux the audio manually, which seems to reduce the utility of this project’s convenience functions.

Did I miss anything?

**Comment by Setsugennoao** [comment]
Hello!
You didn't miss anything, audio demuxing has yet to be implemented.

**Comment by adworacz** [comment]
Got it! Thanks for the quick response. 

In your mind, do you see audio demuxing happening with the native demux support of DGindex etc or some other tool (like pgcdemux)?

**Comment by Setsugennoao** [comment]
This should be moved over vs-muxtools.
