### ISSUE TITLE
get_title only returns the DVD menu.

### ISSUE THREAD

**Issue by Cwavs** [Irrational-Encoding-Wizardry/vs-source#16]
get_title seems to only be returning the9 frame long DVD menu and nothing else.
[VTS_01_0.IFO](http://www.cwavs.xyz/k1Twc7ceAqGjVS0L.IFO) I can provide other files from the DVD if need be as well.

**Comment by Cwavs** [comment]
I've just found another DVD with the same issue, would you like samples from that one as well @Setsugennoao?

**Comment by Setsugennoao** [comment]
Can't reproduce anymore. Issue is > 1year old so probably got fixed with the rewrite.
